### ISSUE TITLE
[BUG] - Servers have no libraries

### ISSUE THREAD

**Issue by tshirtnjeans** [PlexRipper/PlexRipper#326]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

0.15.0

### Platform

Unraid

### Browsers

Google Chrome

### Description

All servers, both owned and shared, do not populate any libraries. Plex credentials are validated, servers connections are checked and connectable. Only throws an error when clicking "Inspect Server"

The plex credentials are valid as it can see the servers associated with acct. but there is some dissonance when trying to access them. 

### Reproduction steps

```bash
Use Setup Wizard
Add Plex account credentials, Validate, Save
Servers populate on sidebar
Drop down to libraries says "No libraries available" on all servers
Click server settings cog
Click "Check server status" ---> multiple "Request Successful!" 
Switch to "Server Commands" Tab
Click "Sync Server Libraries" and "Inspect Server"
Repeat for other servers.
Check log, see error.

Delete all files in /config.
Spin up container ---> all previous user settings and configs load mysteriously from the ether
Delete Plex account profile and add again.
Problem Persists
```

### Logs

```bash
15:14:44 [Error] [DbContextExtensions.PlexAccount.GetPlexAccountsWithAccessAsync:27] => There were no PlexAccounts that have access to PlexServer with id: 4

15:14:44 [Error] [InspectPlexServerJob.Execute:40] => There were no PlexAccounts that have access to PlexServer with id: 4
```

**Comment by JasonLandbridge** [comment]
Hey, the latest version is 0.15. Can you check with that version?

**Comment by bradyloveland** [comment]
> Hey, the latest version is 0.15. Can you check with that version?

Hi, I'm experiencing the same issue.  The version deployed in Unraid appears to be stuck on version .14 and will not update to version .15.  Even when trying to force the update to version .15, no updates are found.  Is it possible that the deployment to Unraid is broken/stuck?

**Comment by tshirtnjeans** [comment]
Confirmed, it's a v0.15.0 issue. 

Unraid doesn't tell you what version container you have anywhere. The template pulls plexripper/plexripper:latest.  I forced an update but it didn't pull any new data. So, I deleted the image and specifically pulled plexripper/plexripper:v0.15.0, The web UI says "PLEXRIPPER - v0.14.0". The library sync issue still exists.

Deleted the v0.15.0 image and pulled v0.14.0 and all libraries populated properly.

**Comment by JasonLandbridge** [comment]
Thanks for the info! I will take a look tomorrow morning!

**Comment by bradyloveland** [comment]
> Confirmed, it's a v0.15.0 issue.
> 
> Unraid doesn't tell you what version container you have anywhere. The template pulls plexripper/plexripper:latest. I forced an update but it didn't pull any new data. So, I deleted the image and specifically pulled plexripper/plexripper:v0.15.0, The web UI says "PLEXRIPPER - v0.14.0". The library sync issue still exists.
> 
> Deleted the v0.15.0 image and pulled v0.14.0 and all libraries populated properly.

I was able to confirm the same on my end.  Deleting the v.15, forcing download v.14, and libraries populate again correctly.

**Comment by JasonLandbridge** [comment]
I managed to fix the issue with the latest version not being deployed, update and ensure you have 0.17 or above running. 

Please try again with loading in your server and libraries, if it still fails then let me know

**Comment by Gabe2K5** [comment]
Just updated the docker on unraid and successfully re-auihenticated my credentials. The issue remains.

**Comment by bradyloveland** [comment]
> I managed to fix the issue with the latest version not being deployed, update and ensure you have 0.17 or above running.
> 
> Please try again with loading in your server and libraries, if it still fails then let me know

I have confirmed that when updating to version .17, the GUI shows that it was updated and the new features appear, but the issue of syncing libraries persists.  I see repeated logs similar to the OP regarding all of the plex servers I have access to.  Rolling back to v .14 resolves the issue.

**Comment by JasonLandbridge** [comment]
@bradyloveland  Could you send me your credentials to [plexripper@protonmail.com](mailto:plexripper@protonmail.com) so i can take a look? There is a years worth of updates between the versions so I have no idea why this is not working.

**Comment by bradyloveland** [comment]
> @bradyloveland Could you send me your credentials to [plexripper@protonmail.com](mailto:plexripper@protonmail.com) so i can take a look? There is a years worth of updates between the versions so I have no idea why this is not working.

I'm not sure how I can send the credentials as I use MFA, but it does seem that the issue is similar to bug 288, but in my case, the servers are found, but I get repeat errors in the logs that there were no plex accounts with access to the plex server.  I didn't have the issue running the docker version on truenas scale jails, but do have the issue with unraid unless I force it to run  v0.14.0

**Comment by JasonLandbridge** [comment]
> I'm not sure how I can send the credentials as I use MFA, but it does seem that the issue is similar to bug #288, but in my case, the servers are found, but I get repeat errors in the logs that there were no plex accounts with access to the plex server. I didn't have the issue running the docker version on truenas scale jails, but do have the issue with unraid unless I force it to run v0.14.0

I have a test account with MFA as well, will try that out. The servers that are missing, are they yours?

**Comment by bradyloveland** [comment]
> > I'm not sure how I can send the credentials as I use MFA, but it does seem that the issue is similar to bug #288, but in my case, the servers are found, but I get repeat errors in the logs that there were no plex accounts with access to the plex server. I didn't have the issue running the docker version on truenas scale jails, but do have the issue with unraid unless I force it to run v0.14.0
> 
> I have a test account with MFA as well, will try that out. The servers that are missing, are they yours?

My server is LovelandPlex, which will not populate, but also the other two servers, which I have access to will not populate.  I get the same error in the logs stating that no plex accounts have access to the server.  I've attached a screenshot of how it should look in v0.14.0.  In v0.17.0, all three show no libraries available.

**Comment by JasonLandbridge** [comment]
Hmmm, could you send an invite to [plexripper@protonmail.com](mailto:plexripper@protonmail.com) for the servers that you own? I just tried to setup my own PlexAccount with MFA and it worked without trouble

**Comment by bradyloveland** [comment]
> Hmmm, could you send an invite to [plexripper@protonmail.com](mailto:plexripper@protonmail.com) for the servers that you own? I just tried to setup my own PlexAccount with MFA and it worked without trouble

I just sent you an invite.  Let me know if you're able to replicate the issue with the unraid release.

**Comment by JasonLandbridge** [comment]
@bradyloveland Thanks! I have indeed been able to recreate the issue on my end. I do see the server but not the libraries, so I will work on a fix as soon as possible!

Thanks for the help!

**Comment by bradyloveland** [comment]
> @bradyloveland Thanks! I have indeed been able to recreate the issue on my end. I do see the server but not the libraries, so I will work on a fix as soon as possible!
> 
> Thanks for the help!

Sounds great, thanks! :)

**Comment by bradyloveland** [comment]
I'm sorry to say that I'm still getting the same error that no accounts have access to the server... Sorry!  I have completely removed the docker container from unraid, deleted the folder/files and re-created it from scratch and still get the same error on version 0.18.0
<img width="1189" alt="Screenshot 2024-08-09 at 10 27 01 AM" src="https://github.com/user-attachments/assets/bd319290-3852-4405-b163-33cf4dae48bc">

**Comment by JasonLandbridge** [comment]
I managed to connect to your LoveAndPlex server from the invite you send me, so I'm a bit lost now. Can you open the server settings of your server => Server Connections and try the little cloud icon next to each connection and see if any of them pass?

You should see at least 6 available connections

**Comment by Gabe2K5** [comment]
I'm also still having the same issue in v .18, my account uses MFA so I wouldn't be able to share it:

Account is validated and enabled:

**Comment by JasonLandbridge** [comment]
@Gabe2K5 Can you try this as well

> I managed to connect to your LoveAndPlex server from the invite you send me, so I'm a bit lost now. Can you open the server settings of your server => Server Connections and try the little cloud icon next to each connection and see if any of them pass?
> 
> You should see at least 6 available connections
> 
And refreshing the page doesn't help anything?

**Comment by Gabe2K5** [comment]
@JasonLandbridge, I don't even have the options you listed in your screenshot, this is what the sidebar looks like for me:

![image](https://github.com/user-attachments/assets/b77cde2a-3e2e-4560-96c4-9fa810cb45f1)


Refreshing the page changes nothing, and restarting the docker results in the same.

**Comment by JasonLandbridge** [comment]
@Gabe2K5 Ah my bad, my last hope is that there might be something in your logs. Can you send me the complete logs to plexripper@protonmail.com? It might help to start from scratch, and re create the account in PlexRipper because then it should log everything

**Comment by Gabe2K5** [comment]
@JasonLandbridge, I just emailed you my logs. I did try uninstalling and reinstalling, but it kept my account from before. I deleted and added the account again, but the result is the same. I've also gotten the same error in Docker Desktop in Windows. I haven't tried it with the latest container, but I'll give it a shot.

**Comment by bradyloveland** [comment]
I show 

> I managed to connect to your **** server from the invite you send me, so I'm a bit lost now. Can you open the server settings of your server => Server Connections and try the little cloud icon next to each connection and see if any of them pass?
> 
> You should see at least 6 available connections
> 


I have 7 connections available and 5 showing green.  It doesn't matter if I select one or leave them unselected, I get the errors shown in my previous screenshot.  I'm happy to email all logs as well if you can tell me where they're located  **nevermind, I found the logs and will email them to you! :).  Here is an updated screenshot showing my 3 plex servers with no libraries - same as before :(

**Comment by JasonLandbridge** [comment]
@Gabe2K5 and @bradyloveland Thank you both very much for the logs! For some reason the authentication token you should get when your credentials are sent to plex.tv is empty/does not exist, and then everything onwards stops working as it cannot get the server/library data. 

I'm not sure why it happens but I will keep investigating

**Comment by JasonLandbridge** [comment]
@Gabe2K5 and @bradyloveland , I have managed to track down the issue. It seems that not all devices have an authentication token, while I assumed they did. I have added filters and extra checks so I hope this is now fixed. Please try again!

**Comment by bradyloveland** [comment]
> @Gabe2K5 and @bradyloveland , I have managed to track down the issue. It seems that not all devices have an authentication token, while I assumed they did. I have added filters and extra checks so I hope this is now fixed. Please try again!

I tried removing the container and starting from scratch and now get this error... any ideas?
<img width="720" alt="Screenshot 2024-08-10 at 9 54 28 PM" src="https://github.com/user-attachments/assets/b8341e85-3f08-417d-9584-e5fa4cdbff29">


**Update: I looked at the logs and for some reason, it doesn't prompt for the MFA code and so I found the option you added to connect using token, so I dug into where I could find the token and connected that way and now it works.  Is this the new intention on how to connect if you use MFA?

**Comment by JasonLandbridge** [comment]
> Is this the new intention on how to connect if you use MFA?

Thanks for reporting back and that is indeed a bug! I have fixed it in the latest version [v0.19.1](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.19.1)

> I found the option you added to connect using token, 

Yes this was an additional request here: https://github.com/PlexRipper/PlexRipper/issues/313

> so I dug into where I could find the token and connected that way and now it works.

Could you share the method you did to find your token? I tried to find a non-technical way but almost everything I found was opening Chrome/Firefox Devtools and digging into network requests.

**Comment by bradyloveland** [comment]
Absolutely, this is how I found the token. Bear in mind, it will only work for a server you have full access/ownership to:

https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by Gabe2K5** [comment]
@JasonLandbridge, progress! I am now able to see servers available, but the libraries are not. When I removed and re-added my account, I was prompted for the MFA pin. I put in the code, and my account successfully validated and my server list populated. Here is a screenshot of what it looks like for me now, I tried manually selecting the external ip address of one of the servers available to me, and it seems to connect, but it still says no libraries available:

**Comment by JasonLandbridge** [comment]
@Gabe2K5 I think I have finally fixed this, it should be working in version [v0.20.0](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.20.0)

**Comment by Gabe2K5** [comment]
@JasonLandbridge, still not quite there yet, but much better now. I can now see the libraries, but anytime I click on one I get the following screen:

![image](https://github.com/user-attachments/assets/a144a0af-d1b0-4fac-97bd-74fb9900f246)

**Comment by JasonLandbridge** [comment]
Ah, it could be that the media is still syncing in the background. You can check the logs if something is happening and or wait a few minutes and then refresh

**Comment by Gabe2K5** [comment]
Does the size of the libraries have an impact on how long the process should take? I've had the docker running for almost an hour and just refreshed the page, but same result.

**Comment by JasonLandbridge** [comment]
@Gabe2K5 Can you send me your auth token privately so I can try it out myself? You can find it here:

![image](https://github.com/user-attachments/assets/36d3a85b-3b62-4ebf-9e2d-9894fbcf55bb)
![image](https://github.com/user-attachments/assets/736e21d4-8e54-41bb-82bf-45fe4bee047b)

**Comment by Gabe2K5** [comment]
@JasonLandbridge, I found the issue, when I originally added my account, I did it with the password and MFA authentication. In looking for my token per your instructions, I saw the option to add my account using the token in the first place. I deleted the account, and re-added it using the token and now the libraries are populating except for one server. Of course it's the server I primarily wanted access to. :-) Not sure why this one shows No libraries found and the others all seem to work. I'm running a download at the moment to test and it seems fine.

**Comment by JasonLandbridge** [comment]
@Gabe2K5 The server you're missing, that is a server you can connect too on plex.tv and view media? Because then that is still an issue. All I can think of for now is that you can maybe try to refresh the accounts like this: 
![image](https://github.com/user-attachments/assets/15f09c47-816e-4258-8ea2-248752386119)

Or clear config and try again. If I have your token I can figure it out.

**Comment by Gabe2K5** [comment]
@JasonLandbridge, yes the server I'm trying to get to is accessible from plex.tv. I sent you the plex token

**Comment by JasonLandbridge** [comment]
@Gabe2K5 Thanks for the help! I have released [v0.21.0](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.21.0) which should fix the above issues. Let me know how it goes!

**Comment by Gabe2K5** [comment]
@JasonLandbridge, I just updated, but I still can't access that same server. All other servers are still accessible. Do I need to remove and read the account again or should it just work?

**Comment by JasonLandbridge** [comment]
Best to just remove config and try again

**Comment by Gabe2K5** [comment]
@JasonLandbridge, all set now! I renamed the plexripper folder in the unraid app data folder. After starting the docker everything acted as if it the first launch. Added my account and checked that server library and I now have access to everything!  Thanks for fixing the issue!

**Comment by JasonLandbridge** [comment]
@Gabe2K5 Awesome! Great to hear!
