### ISSUE TITLE
[BUG] - "There are no servers available!" & "No nodes available"

### ISSUE THREAD

**Issue by Geremia** [PlexRipper/PlexRipper#468]
### Checks

- [x] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

V0.31.0-dev-2025-04-27

### Platform

Linux (via Docker)

### Browsers

Firefox (same issue on Chromium)

### Description

I added my Plex.tv credentials to "Plex Accounts", but nothing shows up.

On the left, it says:

>There are no servers available!
>Make sure that you have a Plex account registered in the settings and have selected an account with accessible plex servers in the top right account selector.

In the middle it says "No media items found!".

### Reproduction steps

1. Login to http://localhost:7000/
2. Add my Plex.tv account.
3. Nothing happens.

### Screenshots

`http://localhost:7000/`:
![localhost:7000 main screen](https://github.com/user-attachments/assets/185e4583-9e8f-4ae6-8a12-e40412d46b95)

`http://localhost:7000/settings/accounts`:
![http://localhost:7000/settings/accounts](https://github.com/user-attachments/assets/6c986cc7-6f95-4db1-8323-171f1562f8fa)

### Logs

```log
21:43:30 [Error] [StartDownloadTaskCommand.Handle:42] => The entity of type DownloadTaskGeneric with id 5bbd5a30-e8f5-4ada-ab56-749e07aaefd7 could not be found
 - Metadata:
 -- StatusCode - 404
**MASKED***.

21:43:10 [Information] [AppUserLoginEndpoint.HandleAsync:104] => User ***MASKED*** signed in successfully.

21:45:34 [Information] [AppUserLoginEndpoint.HandleAsync:92] => Attempting to sign in user ***MASKED***.

21:45:35 [Information] [AppUserLoginEndpoint.HandleAsync:104] => User ***MASKED*** signed in successfully.
/run/s6-rc:s6-rc-init:EJINPC/servicedirs/plexripper
```

**Comment by JasonLandbridge** [comment]
Has been fixed in dev release: https://github.com/PlexRipper/PlexRipper/pull/467

**Comment by Geremia** [comment]
@JasonLandbridge 

v0.31.1-dev-2025-06-13 fixes the problem when I add a new account; it validates when I click the validate button.

```
19:48:16 [Information] [PlexSignInCommandHandler.cs:68.ExecuteAsync()] => Successfully retrieved the PlexAccount data for user ***MASKED*** from the PlexApi
```

But I'm still getting the same "There are no servers available!" and "No nodes available".

**Comment by JasonLandbridge** [comment]
Ah, could you send me the token of your account to plexripper@protonmail.com so I can check what is going wrong?

**Comment by Geremia** [comment]
@JasonLandbridge 

> Ah, could you send me the token of your account to [plexripper@protonmail.com](mailto:plexripper@protonmail.com) so I can check what is going wrong?

How do I find the token? I'm just using my Plex.tv username and password.

**Comment by PmNz8** [comment]
I can confirm similar / the same issue. When adding account it ask me for the 2FA code, I provide it and I get email about new plex login from my account (so it is successful) but the reaparr does not see my or friends server content.
It is on the latest version used by docker:

version: "2.0"
services:
  reaparr:
    image: reaparr/reaparr:dev

However, using the Authorization Token made it work correctly.

@Geremia check this out how to get the plex token: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by JasonLandbridge** [comment]
Closing due to staleness, test with latest version and if it still happens make a new issue
